name: CI_build_combined

on: [push, pull_request]

env:
  BUILD_DIR_LIBS_WIN: "c:/_build_libs"
  BUILD_DIR_APP_WIN: "c:/_build"
  BUILD_DIR_LIBS: "_build_libs"
  BUILD_DIR_APP: "_build"


jobs:
  build:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_configuration: [Release]
        build_platform: ["NMake Makefiles JOM", "Ninja"]

    steps:

    - name: Install nmake replacement jom
      run: |
           choco install jom ninja

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Add nmake
      uses: ilammy/msvc-dev-cmd@v1

    - name: generate cmake libs
      run: |
           cmake -G "${{ matrix.build_platform }}" -DCMAKE_BUILD_TYPE="${{ matrix.build_configuration }}" -B "${{ BUILD_DIR_LIBS_WIN }}"  D:\a\AusweisApp\AusweisApp\libs

    - name: build cmake libs
      run: |
           cmake --build "${{ BUILD_DIR_LIBS_WIN }}" --config ${{ matrix.build_configuration }}

    - name: generate cmake
      run: |
           cmake -G "${{ matrix.build_platform }}" -DCMAKE_BUILD_TYPE="${{ matrix.build_configuration }}" -B "${{ BUILD_DIR_APP_WIN }}"  -DCMAKE_PREFIX_PATH=c:\_build_libs\dist D:\a\AusweisApp\AusweisApp

    - name: build cmake
      run: |
           cmake --build "${{ BUILD_DIR_APP_WIN }}" --config ${{ matrix.build_configuration }} --target package
           cmake --install "${{ BUILD_DIR_APP_WIN }}"

    - name: run ctest
      run: |
           ctest --test-dir "${{ BUILD_DIR_APP_WIN }}" --output-on-failure -C "${{ matrix.build_configuration }}"



  build_linux_cmake:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_configuration: [Release]
        build_platform: ["Ninja"]
        build_dir_libs: ["_build_libs"]
        build_dir_app: ["_build"]

    steps:
    - uses: actions/checkout@v4

    - name: Install packages via apt
      run: |
           sudo apt-get update -qq && sudo apt install -y cmake pkg-config libssl-dev libudev-dev libhttp-parser-dev libpcsclite-dev libgl1-mesa-dev libdbus-1-dev libclang-13-dev libclang-14-dev ninja-build

    - name: generate cmake libs
      run: |
           cmake -G "${{ matrix.build_platform }}" -DCMAKE_BUILD_TYPE="${{ matrix.build_configuration }}" -B ${{ matrix.build_dir_libs }}  ./libs

    - name: build cmake libs
      run: |
           cmake --build ${{ matrix.build_dir_libs }} --config ${{ matrix.build_configuration }}

    - name: generate cmake
      run: |
           cmake -G "${{ matrix.build_platform }}" -DCMAKE_BUILD_TYPE="${{ matrix.build_configuration }}" -B ${{ matrix.build_dir_app }} -DCMAKE_PREFIX_PATH=./_build_libs/dist 

    - name: build cmake
      run: |
           cmake --build ${{ matrix.build_dir_app }} --config ${{ matrix.build_configuration }}
           sudo cmake --install ${{ matrix.build_dir_app }}

    - name: run ctest
      run: |
           ctest --test-dir ${{ matrix.build_dir_app }} --output-on-failure -C "${{ matrix.build_configuration }}"


  build_linux_android_cmake:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_configuration: [Release]
        build_platform: ["Unix Makefiles"]
        build_dir_libs: ["_build_libs"]
        build_dir_app: ["_build"]

    steps:
    - uses: actions/checkout@v4

    - name: Install packages via apt
      run: |
           sudo apt-get update -qq && sudo apt install -y cmake pkg-config libssl-dev libudev-dev libhttp-parser-dev libpcsclite-dev libgl1-mesa-dev libdbus-1-dev libclang-13-dev libclang-14-dev ninja-build
           sudo apt -y remove firefox microsoft-edge-stable google-chrome-stable kotlin libmono* mono-runtime

    - name: generate cmake libs
      run: |
           cmake -G "${{ matrix.build_platform }}" -DCMAKE_BUILD_TYPE="${{ matrix.build_configuration }}" -DCMAKE_TOOLCHAIN_FILE=../cmake/android.toolchain.cmake -B ${{ matrix.build_dir_libs }}  ./libs

    - name: build cmake libs
      run: |
           cmake --build ${{ matrix.build_dir_libs }} --config ${{ matrix.build_configuration }}
           cmake --install ${{ matrix.build_dir_libs }}

    - name: generate cmake
      run: |
           cmake -G "${{ matrix.build_platform }}" -DCMAKE_BUILD_TYPE="${{ matrix.build_configuration }}" -DCMAKE_PREFIX_PATH=./_build_libs/dist -DCMAKE_TOOLCHAIN_FILE=../cmake/android.toolchain.cmake -B ${{ matrix.build_dir_app }}

    - name: build cmake
      run: |
           cmake --build ${{ matrix.build_dir_app }} --config ${{ matrix.build_configuration }}
           cmake --install ${{ matrix.build_dir_app }}

    - name: run ctest
      run: |
           ctest --test-dir ${{ matrix.build_dir_app }} --output-on-failure -C "${{ matrix.build_configuration }}"

  build_macos_cmake:

    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        build_configuration: [Release]
        build_platform: ["Ninja"]
        build_dir_libs: ["_build_libs"]
        build_dir_app: ["_build"]

    steps:
    - uses: actions/checkout@v4

    - name: install ninja
      run: |
           brew install ninja

    - name: generate cmake libs
      run: |
           cmake -G "${{ matrix.build_platform }}" -DCMAKE_BUILD_TYPE="${{ matrix.build_configuration }}" -B ${{ matrix.build_dir_libs }}  ./libs

    - name: build cmake libs
      run: |
           cmake --build ${{ matrix.build_dir_libs }} --config ${{ matrix.build_configuration }}

    - name: generate cmake
      run: |
           cmake -G "${{ matrix.build_platform }}" -DCMAKE_BUILD_TYPE="${{ matrix.build_configuration }}" -DCMAKE_PREFIX_PATH=./_build_libs/dist -B ${{ matrix.build_dir_app }}

    - name: build cmake
      run: |
           cmake --build ${{ matrix.build_dir_app }} --config ${{ matrix.build_configuration }}
           cmake --install ${{ matrix.build_dir_app }}

    - name: run ctest
      run: |
           ctest --test-dir ${{ matrix.build_dir_app }} --output-on-failure -C "${{ matrix.build_configuration }}"


  build_ios_cmake:

    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        build_configuration: [Release]
        build_platform: ["Unix Makefiles"]
        build_dir_libs: ["_build_libs"]
        build_dir_app: ["_build"]

    steps:
    - uses: actions/checkout@v4

    - name: generate cmake libs
      run: |
           cmake -G "${{ matrix.build_platform }}" -DCMAKE_BUILD_TYPE="${{ matrix.build_configuration }}" -DCMAKE_TOOLCHAIN_FILE=../cmake/iOS.toolchain.cmake -B ${{ matrix.build_dir_libs }}  ./libs

    - name: build cmake libs
      run: |
           cmake --build ${{ matrix.build_dir_libs }} --config ${{ matrix.build_configuration }}

    - name: generate cmake
      run: |
           cmake -G "${{ matrix.build_platform }}" -DCMAKE_BUILD_TYPE="${{ matrix.build_configuration }}" -DCMAKE_PREFIX_PATH=./_build_libs/dist -DCMAKE_TOOLCHAIN_FILE=../cmake/iOS.toolchain.cmake -B ${{ matrix.build_dir_app }}

    - name: build cmake
      run: |
           cmake --build ${{ matrix.build_dir_app }} --config ${{ matrix.build_configuration }}
           cmake --install ${{ matrix.build_dir_app }}

    - name: run ctest
      run: |
           ctest --test-dir ${{ matrix.build_dir_app }} --output-on-failure -C "${{ matrix.build_configuration }}"
